name: add case to is_even function

on:
  schedule:
    - cron: "10,20,30,40,50,0 * * * *"
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  add-case:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup uv
        uses: astral-sh/setup-uv@v7
      - name: run
        run: for i in {1..5000}; do uv run updater.py; done
      - name: bump
        run: uv version --bump patch
      - name: commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "feat: add until $(cat last)"
          git push
      - name: build
        run: uv build
      - name: publish
        run: uv publish --token ${{ secrets.PYPI_TOKEN }}
